FROM apache/airflow:2.7.0

USER root
RUN apt-get update && \
    apt-get install -y gcc libpq-dev && \
    rm -rf /var/lib/apt/lists/*

COPY requirements-airflow.txt /requirements-airflow.txt
USER airflow
RUN pip install --user --no-cache-dir -r /requirements-airflow.txt
USER root
COPY ./airflow/dags    /opt/airflow/dags
COPY ./airflow/plugins /opt/airflow/plugins
COPY ./spark/scripts   /opt/airflow/scripts
COPY ./jars            /opt/airflow/jars
COPY ./mlops /opt/airflow/mlops
RUN chown -R airflow: /opt/airflow

USER airflow
