version: '3.8'
services:

  postgres:
    image: postgres:15
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  spark-master:
    build:
      context: .
      dockerfile: Dockerfile-spark
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8081:8081"
    volumes:
      - ./data/raw:/opt/data/raw
      - ./jars:/opt/bitnami/spark/jars

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile-spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./data/raw:/opt/data/raw
      - ./jars:/opt/bitnami/spark/jars

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile-airflow
    env_file: .env
    depends_on:
      - postgres
      - spark-master
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
      - ./spark/scripts:/opt/airflow/scripts
      - ./jars:/opt/airflow/jars
      - ./data/raw:/opt/data/raw
    command: webserver

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile-airflow
    env_file: .env
    depends_on:
      - airflow-webserver
      - postgres
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
      - ./spark/scripts:/opt/airflow/scripts
      - ./jars:/opt/airflow/jars
      - ./data/raw:/opt/data/raw
    command: scheduler

  general:
    build:
      context: .
      dockerfile: Dockerfile-general
    volumes:
      - ./streamlit_app:/app
    ports:
      - "8501:8501"
    depends_on:
      - postgres

volumes:
  postgres_data:
