FROM bitnami/spark:3.4

USER root
RUN apt-get update && apt-get install -y gcc libpq-dev && rm -rf /var/lib/apt/lists/*
ENV PIP_ROOT_USER_ACTION=ignore

COPY requirements-spark.txt /requirements-spark.txt
RUN pip install --no-cache-dir -r /requirements-spark.txt

COPY ./jars/postgresql-42.5.0.jar       /opt/bitnami/spark/jars/
COPY ./spark/scripts/etl_spark.py       /opt/bitnami/spark/app/etl_spark.py

RUN chown -R 1001:1001 /opt/bitnami/spark/jars /opt/bitnami/spark/app
USER 1001